# Generated by Django 3.2.2 on 2021-05-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='location',
            field=models.CharField(default='remote', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobpost',
            name='salary',
            field=models.CharField(default='30K / month', max_length=300),
            preserve_default=False,
        ),
    ]
