# Generated by Django 3.2.2 on 2021-06-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="fields",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Field", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="courses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("posted_on", models.DateTimeField(auto_now=True)),
                ("link", models.URLField(max_length=10000)),
                ("price", models.IntegerField()),
                (
                    "Field",
                    models.ManyToManyField(related_name="fields", to="courses.fields"),
                ),
            ],
        ),
    ]
