# Generated by Django 3.2.2 on 2021-05-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="courses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("link", models.CharField(max_length=10000)),
                ("price", models.IntegerField()),
                ("Field", models.CharField(max_length=200)),
            ],
        ),
    ]
