# Generated by Django 3.2.2 on 2021-05-26 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Field', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='courses',
            name='Field',
        ),
        migrations.AddField(
            model_name='courses',
            name='Field',
            field=models.ManyToManyField(to='courses.fields'),
        ),
    ]
